### ISSUE TITLE
Object of state "vodafone-speedtest.0.modem" is missing the required property "common.type"

### ISSUE THREAD

**Issue by Grothesk242** [peterbaumert/ioBroker.vodafone-speedtest#15]
Log file shows

`vodafone-speedtest.0 (26555) Object of state "vodafone-speedtest.0.modem" is missing the required property "common.type"`

**Versions:**  
 - Adapter version: 0.0.6
 - JS-Controller version: 3.3.5
 - Node version: v14.16.1
 - Operating system: Linux / Raspberry OS 'Buster'

**Comment by peterbaumert** [comment]
fixed in 0.7.0
