### ISSUE TITLE
Fehler im Log

### ISSUE THREAD

**Issue by CKMartens** [peterbaumert/ioBroker.vodafone-speedtest#8]
Ich benutze die Version 0.0.5, mit dem js-Controler 3.1.6

In den Settings sind für den Adapter die Standartcronzeiten 3,11,41 eingetrage. Zu den angegebene Zeiten taucht im Log immer die folgene Fehlermeldung auf:

```
host.iob01 | 2020-09-19 12:11:00.219 | error | instance system.adapter.vodafone-speedtest.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
```

Eine Neuinstallation des Adapters hat leider nicht zu einer Verbesserung geführt.

**Comment by Flyor** [comment]
Ich kann mich dem Fehler anschließen. Bei mir hat der Adapter monatelang einwandfrei funktioniert, seit dem Update auf Node 12 (vorher 10) funktioniert er leider nicht mehr. JS Controller ist ebenfalls auf 3.1.6 und ich nutze ebenfalls Adapter Version 0.0.5

![1](https://user-images.githubusercontent.com/64526892/95443169-8ea8cb00-095c-11eb-8918-0cab99e15359.jpg)

**Comment by Grothesk242** [comment]
Hier gibt es auch Probleme mit aktuellsten nodeJS Versionen (15.1.0)
Mit node12 und node14 jedoch keine Probleme. 
Leider gibt es auch auf log level 'debug' nichts verwertbares im Log: 

```
2020-11-11 13:54:34.359  - info: host.raspberrypi "system.adapter.vodafone-speedtest.0" enabled
2020-11-11 13:54:34.361  - info: host.raspberrypi stopInstance system.adapter.vodafone-speedtest.0 (force=false, process=false)
2020-11-11 13:54:37.380  - info: host.raspberrypi instance scheduled system.adapter.vodafone-speedtest.0 11,41 * * * *
2020-11-11 13:56:30.547  - info: host.raspberrypi stopInstance system.adapter.vodafone-speedtest.0 (force=false, process=false)
2020-11-11 13:56:30.553  - info: host.raspberrypi stopInstance canceled schedule system.adapter.vodafone-speedtest.0
2020-11-11 13:56:33.594  - info: host.raspberrypi instance scheduled system.adapter.vodafone-speedtest.0 11,41 * * * *
2020-11-11 14:11:00.038  - info: host.raspberrypi instance system.adapter.vodafone-speedtest.0 started with pid 10226
2020-11-11 14:11:00.566  - error: host.raspberrypi instance system.adapter.vodafone-speedtest.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2020-11-11 14:11:54.693  - info: host.raspberrypi stopInstance system.adapter.vodafone-speedtest.0 (force=false, process=false)
2020-11-11 14:11:54.694  - info: host.raspberrypi stopInstance canceled schedule system.adapter.vodafone-speedtest.0
2020-11-11 14:11:57.722  - info: host.raspberrypi instance scheduled system.adapter.vodafone-speedtest.0 11,41 * * * *
```

**Comment by peterbaumert** [comment]
Schaue es mir die Tage mal an.

**Comment by NebuNC2** [comment]
@peterbaumert hattest du schon die Zeit dir das anzusehen?

**Comment by jk-andersen** [comment]
Habe gleiches Verhalten mit Node 14.15.4 - Funktioniert nur nach einem kompletten Neustart des Hosts.

`

host.iobroker | 2021-01-14 09:22:00.122 | error | instance system.adapter.vodafone-speedtest.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --


`

**Comment by peterbaumert** [comment]
habe es noch nicht wirklich nachstellen können :( node 15 habe ich aber auch ehrlich gesagt noch nicht getestet da iobroker erstmal nur bis 14 "supportet".

Habt ihr nach den updates denn die node module rebuiled?

**Comment by peterbaumert** [comment]
ok habe es nun doch hinbekommen
```
npm rebuild
npm install
```

diese beiden befehle im `iobroker/node_modules/iobroker.vodafone-speedtest` ordner ausführen

**Comment by jk-andersen** [comment]
> ok habe es nun doch hinbekommen
> 
> ```
> npm rebuild
> npm install
> ```
> 
> diese beiden befehle im `iobroker/node_modules/iobroker.vodafone-speedtest` ordner ausführen

Kann die Lösung positiv bestätigen mit node 14.5.4

**Comment by NebuNC2** [comment]
Wie muss ich das verstehen?

diese beiden befehle im iobroker/node_modules/iobroker.vodafone-speedtest ordner ausführen

in welchem Ordner und wie ausführen?

**Comment by peterbaumert** [comment]
> Wie muss ich das verstehen?
> 
> diese beiden befehle im iobroker/node_modules/iobroker.vodafone-speedtest ordner ausführen
> 
> in welchem Ordner und wie ausführen?

Hast du Windows oder Linux?

Du musst mit der Kommandozeile in deinen ioBroker Installationsordner und dann in den Unterordner "/node_modules/iobroker.vodafone-speedtest" und dann die beiden Befehle eingeben.

**Comment by NebuNC2** [comment]
Und wieder nur Bahnhof verstanden...
Iobroker läuft bei mir auf einem Raspberry Pi mit Linux.

wie komme ich denn da genau hin?

**Comment by CKMartens** [comment]
Bei mir ist der Fehler aber aufgetreten ohne das ich ein Nodes-Update bzw. js-Controler Update gemacht hatte. Der Fehler ist durch den Workaround behoben.

**Comment by peterbaumert** [comment]
> Bei mir ist der Fehler aber aufgetreten ohne das ich ein Nodes-Update bzw. js-Controler Update gemacht hatte. Der Fehler ist durch den Workaround behoben.

Ja irgendwas ist da komisch. Ich schaue mir das genauer an aber so ganz reproduzieren kann ich es nicht zuverlässig.

**Comment by CKMartens** [comment]
Der Fehler ist immer noch im Log vorhanden. js-Controller 3.2.8 und Adaper-Version 0.0.6.

```
host.iob01 | 2021-01-23 08:03:00.449 | error | instance system.adapter.vodafone-speedtest.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
```

Der in diesem Issue angegebene workaround wurde erfolglos angewand.

**Comment by peterbaumert** [comment]
> Der Fehler ist immer noch im Log vorhanden. js-Controller 3.2.8 und Adaper-Version 0.0.6.
> 
> ```
> host.iob01 | 2021-01-23 08:03:00.449 | error | instance system.adapter.vodafone-speedtest.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
> -- | -- | -- | --
> ```
> 
> Der in diesem Issue angegebene workaround wurde erfolglos angewand.

was kommt denn wenn du im iobroker verzeichniss `node node_modules/iobroker.vodafone-speedtest/main.js --force --logs` ausführst?

**Comment by CKMartens** [comment]
Hallo,
in der Konsole kommt folgendes Log:
```
2021-01-23 15:41:11.955  - info: vodafone-speedtest.0 (7621) starting. Version 0                                                            .0.6 in /opt/iobroker/node_modules/iobroker.vodafone-speedtest, node: v12.20.1,                                                             js-controller: 3.2.8
2021-01-23 15:41:41.980  - info: vodafone-speedtest.0 (7621) Vodafone-Speedtest finished with 82.59mbit download speed and 29.894mbit upload speed.
2021-01-23 15:41:41.985  - info: vodafone-speedtest.0 (7621) cleaned everything up...
2021-01-23 15:41:42.034  - info: vodafone-speedtest.0 (7621) Terminated (NO_ERROR): Without reason
```

Im Log von ioBroker kam allerdings um 
```
host.iob01 | 2021-01-23 15:41:01.159 | error | instance system.adapter.vodafone-speedtest.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
```
Was mich jetzt vermuten lässt das ich ein Problem mit einer zweiten Instanz habe.

**Comment by NebuNC2** [comment]
Könntet ihr für ganz blöde nochmal erklären wie ich das hinbekomme?

Du musst mit der Kommandozeile in deinen ioBroker Installationsordner und dann in den Unterordner "/node_modules/iobroker.vodafone-speedtest" und dann die beiden Befehle eingeben.

Ich benutze einen Raspberry Pi. Habe aber überhaupt keine Ahnung wie ich das machen soll...

**Comment by peterbaumert** [comment]
> Hallo,
> in der Konsole kommt folgendes Log:
> 
> ```
> 2021-01-23 15:41:11.955  - info: vodafone-speedtest.0 (7621) starting. Version 0                                                            .0.6 in /opt/iobroker/node_modules/iobroker.vodafone-speedtest, node: v12.20.1,                                                             js-controller: 3.2.8
> 2021-01-23 15:41:41.980  - info: vodafone-speedtest.0 (7621) Vodafone-Speedtest finished with 82.59mbit download speed and 29.894mbit upload speed.
> 2021-01-23 15:41:41.985  - info: vodafone-speedtest.0 (7621) cleaned everything up...
> 2021-01-23 15:41:42.034  - info: vodafone-speedtest.0 (7621) Terminated (NO_ERROR): Without reason
> ```
> 
> Im Log von ioBroker kam allerdings um
> 
> ```
> host.iob01 | 2021-01-23 15:41:01.159 | error | instance system.adapter.vodafone-speedtest.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
> -- | -- | -- | --
> ```
> 
> Was mich jetzt vermuten lässt das ich ein Problem mit einer zweiten Instanz habe.

Hm okay, und du hast die befehle mit dem iobroker user ausgeführt oder mit root?

**Comment by rof999** [comment]
Jau, das funktioniert. Vielen Dank.

Aber der o.g. Pfad ist nicht ganz richtig.

Siehe:

`cd /opt/iobroker/node_modules/iobroker.vofo-speedtest
npm rebuild
npm install
`

**Comment by Grothesk242** [comment]
Ja, der Adapter musste zwischenzeitlich aus markenrechtlichen Gründen umbenannt werden.
